Mosh/Beg-Python/vidly/movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.index, name='index'),
    # we have set django to apply this behavior:
    # movies/movie_id
    # make sure it's an integer
    # no need for movies_index and movies_detail
    # the app_name property insure that django will
    # know our to deals with these urls.
    path('<int:movie_id>', views.detail, name='detail')
]

Mosh/Beg-Python/vidly/vidly/urls.py
from django.contrib import admin
from django.urls import path, include
from api.models import MovieResource, GenreResource
from . import views

movie_resource = MovieResource()
genre_resource = GenreResource()

urlpatterns = [
    # homepage
    path('', views.home),
    # admin and moveis
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    # api expose
    path('api/', include(movie_resource.urls)),
    path('api/', include(genre_resource.urls))
]

Mosh/Beg-Python/vidly/api/models.py
from django.db import models
from tastypie.resources import ModelResource
from movies.models import Movie, Genre
# Build REST API (resources)


class MovieResource(ModelResource):
    class Meta:
        # lazy loading
        queryset = Movie.objects.all()
        # will help with `/movie/api/movie`
        resource_name = "movies"
        excludes = ['date_created']


class GenreResource(ModelResource):
    class Meta:
        # lazy loading
        queryset = Genre.objects.all()
        # will help with `/movie/api/movie`
        resource_name = "genres"

Mosh/Beg-Python/vidly/movies/models.py
from django.db import models
from django.utils import timezone
# Create your models here.


class Genre(models.Model):
    # use field
    name = models.CharField(max_length=255)
    # override the default __str__

    def __str__(self):
        return self.name


class Movie(models.Model):
    # use field
    title = models.CharField(max_length=255)
    release_year = models.IntegerField()
    number_in_stock = models.IntegerField()
    daily_rate = models.FloatField()
    # association has-many and belongs to
    # on delete will tell django how to handle
    # a delete event of a genre given the
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE)
    # add a new
    date_created = models.DateTimeField(default=timezone.now)
    # override the default __str__

    # def __str__(self):
    #   return self.name

Mosh/Beg-Python/vidly/api/views.py
from django.shortcuts import render

# Create your views here.

Mosh/Beg-Python/vidly/movies/views.py
from django.http import HttpResponse, Http404
from django.shortcuts import render, get_object_or_404
from .models import Movie

# Create your views here.


def index(request):
    movies = Movie.objects.all()
    #output = " ".join([m.title for m in movies])
    # return HttpResponse(output)
    return render(request, 'movies/index.html', {'movies': movies})


def detail(request, movie_id):
    #movie = Movie.objects.get(id=movie_id)
    movie = get_object_or_404(Movie, id=movie_id)
    return render(request, 'movies/detail.html', {'movie': movie})


# we must create our template now
# create a urls.py to mapp this index

Mosh/Beg-Python/vidly/vidly/views.py
from django.shortcuts import render

def home(request):
    return render(request,'home.html')


# We need to map this views to our url endpoint

Mosh/Beg-Python/vidly/movies/templates/movies/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>Vidly Movie Application</title>
  </head>
  <body>
    {% block content %}
    {% endblock  %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

Mosh/Beg-Python/vidly/movies/templates/movies/detail.html
{% extends 'base.html' %}

{% block content %}
<dl>
    <dt>Title</dt>
    <dd>{{movie.title}}</dd>
    <dt>Genre</dt>
    <dd>{{movie.genre}}</dd>
    <dt>Stock</dt>
    <dd>{{movie.number_in_stock}}</dd>
</dl>
{% endblock  %}

Mosh/Beg-Python/vidly/movies/templates/movies/index.html
    {% extends 'base.html' %}
    {% block content %}
    <table class="table table-bordered table-hover">
        <thead>
            <th>Title</th>
            <th>Genre</th>
            <th>Stock</th>
            <th>Daily Rate</th>
        </thead>
        <tbody>
            {% for movie in movies %}
                <tr>
                    <td><a href="{% url 'movies:detail' movie.id%}">{{movie.title}}</a></td>
                    <td>{{movie.genre}}</td>
                    <td>{{movie.number_in_stock}}</td>
                    <td>{{movie.daily_rate}}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% endblock  %}
      

Mosh/Beg-Python/vidly/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>Vidly Movie Application</title>
  </head>
  <body>
    <nav class="navbar navbar-light bg-light">
      <a class="navbar-brand" href="#">Vidly</a>
    </nav>
    <main class="container">
    {% block content %}
    {% endblock  %}
    </main>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

Mosh/Beg-Python/vidly/templates/home.html
{% extends 'base.html' %}

{% block content %}
<h1> Welcome to the Vidly movie application</h1>
<a href='{% url 'movies:index' %}'>See your movies</a>
{% endblock  %}